### ISSUE TITLE
Trigger repository re-scan from client

### ISSUE THREAD

**Issue by benjamin-heasly** [isetbio/RemoteDataToolbox#45]
The Archiva RESTful API allows a client to trigger a repository re-scan.  This exists at the resource path:

```
'/restServices/archivaServices/repositoriesService/scanRepositoryNow';
```

We should have a utility for this!  It should be simple, for example:

```
status = rdtRequestRepositoryRescan(configuration)
```

We could invoke this utility automatically when publishing to or deleting from a repository.

**Comment by benjamin-heasly** [comment]
Here is some sandbox code that seemed to work.

```
%% Trigger a scan!
configuration = rdtCredentialsDialog(rdtConfiguration('brainard-archiva'));
configuration.acceptMediaType = 'text/plain';
configuration.repositoryName = 'scien';
resourcePath = '/restServices/archivaServices/repositoriesService/scanRepositoryNow';
queryParams = struct( ...
    'repositoryId', configuration.repositoryName, ...
    'fullScan', 1);
response = rdtRequestWeb(configuration, resourcePath, 'queryParams', queryParams);
```

Playing with this, it seems that triggering a rescan is restricted to repository administrators, which seems reasonable.

**Comment by DavidBrainard** [comment]
Sounds cool, but I don't know what a rescan does.  What does a rescan do?

**Comment by benjamin-heasly** [comment]
Aha!

A rescan updates the server's index of what is available.  This is needed for accurate results when listing or searching for artifacts from the Matlab client.  This probably also applies to the Web UI (aka dot urls).

Rescanning would not affect fetching of actual data.  It also would not affect the plain HTML lists of artifacts (aka slash urls).

Currently we have to trigger a rescan by logging in and clicking buttons.  Or we can wait 0-60 minutes until the next hourly scan happens.

So this would be most useful when publishing or deleting artifacts, or running system tests.  It should reduce head-scratching of the flavor "What do you mean it's not listed?  I just published it!"

**Comment by benjamin-heasly** [comment]
Here is a little wrinkle:

In order to trigger a rescan, the user must have a permission called "run indexer".  This is a different permission from the usual "repository manager" permission which allows writing to a repository.

So if the user is not configured correctly, the rescan will fail.  The client utility should expect this kind of failure to happen sometimes, and not fail dramatically.  It should just report, "sorry, you can't do that" in an unobtrusive way.

**Comment by wandell** [comment]
This feels important to me now because I was just testing code for the pull request on the deleteArtifacts branch (which looks great).  But it is very disconcerting for the artifacts to still be there in the browser after they are deleted from the Matlab commands.  As I write this, I am still not sure that the remote server executed the deletes as requested, even though the delete calls seemed to run OK.  But I stil see the artifacts and paths on the remote server.

So, maybe we should wait to merge the deleteArtifacts until we can also trigger a remote scan?

**Comment by wandell** [comment]
Just a little timing note - I ran the delete commands about 2 hours ago.  At this point, they may or may not have worked (even though I did the merge).  I still see the artifacts and path.  I am just hoping that the database hasn't updated yet, but the commands ran fine.  That's what I believe, anyway.

**Comment by benjamin-heasly** [comment]
Huh.  What artifacts did you delete?  I would like to take a look from my end to see what happened.

My expectation is the the raw HTML view of artifacts (aka slash Urls) should be updated immediately following a delete.  So if this view still shows the artifacts, then something else must have gone wrong with the delete.

Same goes for trying to `readArtifact(s)` -- this should fail immediately following a delete.  So if you can still `readArtifact()` then something else must have gone wrong. :-1: 

Nevertheless, I agree we want to re-scan, for the sake of the Web UI (aka dot Urls) and the list and search functions from Matlab.  So I'll get started! :+1:

**Comment by benjamin-heasly** [comment]
https://github.com/isetbio/RemoteDataToolbox/pull/55 adds a re-scan utility.  It's integrated with publishing and deleting functions so re-scans should happen automatically at useful times.

It looks like this is working on my end.  How does it look to you?

**Comment by wandell** [comment]
LGTM
